### PR TITLE
solution

### PR DESCRIPTION
**Pull request by snuber-w**
- [DEMO LINK](https://snuber-w.github.io/react_person/)

### CODE REVIEW

**Review by 33Orange — COMMENTED** [review]
image

You didn't add person.scss

**Review by 33Orange — CHANGES_REQUESTED** [review]
Almost done.

Fix prev comment please

**Comment by snuber-w** [comment]
I mistakenly didn't add the styles to the commit 👀

**Review by 33Orange — APPROVED** [review]
Well done

**Pull request closed without merging**
